# -*- coding: utf-8 -*-
"""Analise de vendas com Grafico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1poITFMmNWmhUWL7b8Ai6j8v1paI2QAcz
"""

import os
import pandas as pd
import plotly.express as px
lista_arquivos = os.listdir("/content/drive/MyDrive/dev/python/Vendas")
#display(lista_arquivos)

tabela_total =pd.DataFrame()

#passo 2

for arquivo in lista_arquivos:
  if 'vendas' in arquivo.lower():
    tabela = pd.read_csv(f"/content/drive/MyDrive/dev/python/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela)
  
  #passo 3
# display(tabela_total)

#passo 4 - Calcular produto mais vendido

tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=True)

#5 Calcular o produto que mais faturou
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']
tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending=True)

#6 Calcular Loja que mais faturou
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']].sort_values(by="Faturamento", ascending=True)
display(tabela_lojas)

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()